# Generated by Django 4.0.6 on 2022-07-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodtracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moodentry',
            name='mood',
            field=models.CharField(choices=[('CALM', 'Calm'), ('EXCITED', 'Excited'), ('ANGRY', 'Angry'), ('SAD', 'Sad'), ('FRUSTRATED', 'Frustrated'), ('SCARED', 'Scared'), ('RESTED', 'Rested'), ('HAPPY', 'Happy'), ('TIRED', 'Tired')], max_length=10),
        ),
    ]
