# Generated by Django 4.0.6 on 2022-07-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodtracker', '0002_alter_moodentry_mood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moodentry',
            name='mood',
            field=models.CharField(choices=[('CALM', 'Calm'), ('EXCITED', 'Excited'), ('ANGRY', 'Angry'), ('SAD', 'Sad'), ('FRUSTRATED', 'Frustrated'), ('SCARED', 'Scared'), ('RESTED', 'Rested'), ('HAPPY', 'Happy'), ('TIRED', 'Tired')], help_text='How are you feeling today?', max_length=10),
        ),
        migrations.AlterField(
            model_name='moodentry',
            name='mood_influences',
            field=models.TextField(blank=True),
        ),
    ]
