# Generated by Django 4.0.6 on 2022-07-11 11:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('moodtracker', '0004_alter_moodentry_date_alter_moodentry_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moodentry',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='moodentry',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
