# Generated by Django 4.0.6 on 2022-07-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodtracker', '0005_alter_moodentry_date_alter_moodentry_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moodentry',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
