# Generated by Django 4.0.6 on 2022-07-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodtracker', '0006_alter_moodentry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moodentry',
            name='date',
        ),
        migrations.AlterField(
            model_name='moodentry',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
